# Loco yaml export: Generic nested YAML object
# Project: application.properties conversion
# Release: Working copy
# Locale: en-AU, English (Australia)
# Exported by: Unregistered user
# Exported at: Sun, 08 Aug 2021 09:34:20 +1000
---
en-AU:
  application:
    spring:
      datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: ""
      jpa:
        hibernate:
          ddl-auto: none
        database-platform: org.hibernate.dialect.H2Dialect
      h2:
        console:
          enabled: "true"
      data:
        jpa:
          repositories:
            bootstrap-mode: default
    management:
      endpoints:
        jmx:
          exposure:
            include: health
...
