DROP TABLE IF EXISTS CUSTOMER_PHONE_NUMBER;
DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER(
    ID VARCHAR(15)  PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(40) NOT NULL
);


CREATE TABLE CUSTOMER_PHONE_NUMBER(
     CUSTOMER_PHONENUMBER VARCHAR(15) PRIMARY KEY,
     ID VARCHAR(15),
     ACTIVATION_STATUS VARCHAR(5),
     FOREIGN KEY (ID) REFERENCES CUSTOMER(ID)
);